{% set name = "pypdfium2" %}
{% set version = "4.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///Users/jolivieri/repos/upstream/pypdfium2/dist/pypdfium2-4.18.0.tar.gz
  sha256: 409ac0e65ff02c56f28879cdb10846a65c916f79e9b6b32d4975daa6c7450bbb

build:
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - build
    - wheel !=0.38.0,!=0.38.1
    - ctypesgen
    - pip
  run:
    - python

test:
  imports:
    - pypdfium2
  commands:
    - pip check
    - pypdfium2 --help
  requires:
    - pip

about:
  summary: Python bindings to PDFium
  description: |
    pypdfium2 is an ABI-level Python 3 binding to PDFium, a powerful and liberal-licensed library for PDF rendering,
    inspection, manipulation and creation.
  license: Apache-2.0
  license-files:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LicenseRef-PdfiumThirdParty.txt
    - LICENSES/CC-BY-4.0.txt
    - .reuse/dep5
  doc_url: https://pypdfium2.readthedocs.io/en/stable
  dev_url: https://github.com/pypdfium2-team/pypdfium2

extra:
  recipe-maintainers:
    - boldorider4
