{% set name = "pypdfium2" %}
{% set version = "4.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypdfium2-team/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c937121dc475942697fbb3e04ffa7b28d36afc2b76cc9aac22fbd327c6dc6d61

build:
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - git  # [not win]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - build
    - wheel !=0.38.0,!=0.38.1
    - ctypesgen-pypdfium2-team 1.1.1+4_g8a62d02
    - pdfium-binaries 118.0.5868
  run:
    - python
    - pdfium-binaries 118.0.5868

test:
  imports:
    - pypdfium2
  commands:
    - pip check
    - pypdfium2 --help
  requires:
    - pip

about:
  summary: Python bindings to PDFium
  description: |
    pypdfium2 is an ABI-level Python 3 binding to PDFium, a powerful and liberal-licensed library for PDF rendering,
    inspection, manipulation and creation.
  license: Apache-2.0
  license-files:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LicenseRef-PdfiumThirdParty.txt
    - LICENSES/CC-BY-4.0.txt
    - .reuse/dep5
  doc_url: https://pypdfium2.readthedocs.io/en/stable
  dev_url: https://github.com/pypdfium2-team/pypdfium2

extra:
  recipe-maintainers:
    - boldorider4
