{% set name = "pypdfium2" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9febb09f532555485f064c1f6442f46d31e27be5981359cb06b5826695906a06

build:
  skip: True  # [win or (linux and (s390x or ppc64le))]
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script_env:
    - PDFIUM_PLATFORM=system-search
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - packaging
    - pip
    - wheel
    - ctypesgen-pypdfium2-team >=5.4.0
    - pdfium 7776
  run:
    - python
    - pdfium 7776

test:
  imports:
    - pypdfium2
  commands:
    - pip check
    - pypdfium2 --help
  requires:
    - pip

about:
  home: https://github.com/pypdfium2-team/pypdfium2
  summary: Python bindings to PDFium
  description: |
    pypdfium2 is an ABI-level Python 3 binding to PDFium, a powerful and liberal-licensed library for PDF rendering,
    inspection, manipulation and creation.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/CC-BY-4.0.txt
  doc_url: https://pypdfium2.readthedocs.io/en/stable
  dev_url: https://github.com/pypdfium2-team/pypdfium2

extra:
  recipe-maintainers:
    - boldorider4
